apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescale-cluster
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 10Gi
