apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hetida-platform-dev

resources:
  - ../../base/hetida-platform-dev
  - longhorn-storageclass.yaml
  - external-secrets/secret-store.yaml
  - external-secrets/s3-creds.yaml
  - external-secrets/db-secrets.yaml
  - pooler.yaml
  - network-policy.yaml
  - alertmanager-teams-config.yaml

patches:
  - path: cluster-patch.yaml
  - path: cluster-backup-patch.yaml
