apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetida-platform-secrets
  namespace: hetida-platform-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: hetida-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: timescaledb/prod/database
        property: username
    - secretKey: password
      remoteRef:
        key: timescaledb/prod/database
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-superuser-secret
  namespace: hetida-platform-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: cnpg-superuser-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: timescaledb/prod/superuser
        property: username
    - secretKey: password
      remoteRef:
        key: timescaledb/prod/superuser
        property: password
