apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: hetida-platform-dev
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: hetida-platform-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
