apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-crds-backup.yaml
  - cnpg-crds-clusterimagecatalog.yaml
  - cnpg-crds-clusterlist.yaml
  - cnpg-crds-imagecataloglist.yaml
  - cnpg-crds-poolerlist.yaml
  - cnpg-crds-scheduledbackup.yaml