apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Secrets and environment-specific resources are provided by overlays.
resources:
  - cluster.yaml
  - podmonitor.yaml
  - backup-daily.yaml
  - backup-monitor.yaml
  - postgres-monitor.yaml
  - grafana-dashboard.yaml
  - grafana-backup-dashboard.yaml
