apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescale-restore-test
  namespace: hetida-platform-dev
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16-ts
  bootstrap:
    recovery:
      source: timescaledb
      recoveryTarget:
        targetImmediate: true
  storage:
    size: 10Gi
    storageClass: longhorn
  resources:
    requests:
      memory: '512Mi'
      cpu: '200m'
    limits:
      memory: '1Gi'
      cpu: '500m'
  externalClusters:
    - name: timescaledb
      barmanObjectStore:
        destinationPath: 's3://backups/timescaledb/'
        endpointURL: 'http://minio.minio-system.svc.cluster.local:9000'
        s3Credentials:
          accessKeyId:
            name: s3-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: s3-creds
            key: SECRET_ACCESS_KEY
