apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb
spec:
  instances: 2
  minSyncReplicas: 1
  maxSyncReplicas: 1
  storage:
    size: 20Gi
    storageClass: longhorn-dev
  resources:
    requests:
      memory: '1Gi'
      cpu: '250m'
    limits:
      memory: '2Gi'
      cpu: '1'
  backup:
    retentionPolicy: '7d'
